version: '3.7'
services:
  dashboard:
    build: .
    image: seosnap-dashboard
    container_name: seosnap_dashboard
    restart: unless-stopped
    environment:
      DB_HOST_OVERRIDE: db
      DB_ROOT_HOST:
      DB_HOST:
      DB_NAME:
      DB_USER:
      DB_PASS:
      ADMIN_EMAIL:
      ADMIN_NAME:
      ADMIN_PASS:
      ADMIN_SECRET:
      ADMIN_DEBUG:
      ADMIN_LOG_LEVEL:
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - seosnap_dashboard

  db:
    image: mysql
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: ${DB_ROOT_HOST}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - seosnap_dashboard_db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - seosnap_dashboard

volumes:
  seosnap_dashboard_db:

networks:
  seosnap_dashboard:
    driver: bridge
