# Generated by Django 3.1.12 on 2022-02-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seosnap', '0006_auto_20220208_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='x_magento_tags',
            field=models.TextField(),
        ),
    ]
